networks:
  dataengine-network:
    name: dataengine-network

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template
    restart: always
    depends_on:
      aas-template-registry:
        condition: service_healthy
      sm-template-registry:
        condition: service_healthy
      template-repository:
        condition: service_healthy
    networks:
      - dataengine-network

  twinengine-dataengine:
    build:
      context: ../../
      dockerfile: ./AAS.TwinEngine.DataEngine/Dockerfile
    image: twinengine-dataengine:latest
    ports:
    - '8085:8080'
    container_name: twinengine-dataengine
    depends_on:
      twinengine-plugin:
        condition: service_started
    restart: always
    environment:
      - General__DataEngineRepositoryBaseUrl=http://localhost:8080
      - General__CustomerDomainUrl=https://mm-software.com
      - Plugins__Instances__0__Name=TestPlugin
      - Plugins__Instances__0__baseUrl=http://twinengine-plugin:8080
      - Plugins__Instances__0__headerMappings__0__source=Authorization
      - Plugins__Instances__0__headerMappings__0__target=X-Auth-Token
      - Plugins__Instances__0__headerMappings__0__required=false
      - Plugins__Instances__0__headerMappings__1__source=X-Organization-Id
      - Plugins__Instances__0__headerMappings__1__target=X-Tenant-Context
      - Plugins__Instances__0__headerMappings__1__required=false
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__0__templateId=https://admin-shell.io/idta/SubmodelTemplate/HandoverDocumentation/2/0
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__0__pattern__0=HandoverDocumentation
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__1__templateId=https://admin-shell.io/idta/SubmodelTemplate/ContactInformation/1/0
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__1__pattern__0=ContactInformation
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__2__templateId=https://admin-shell.io/idta/CustomSubmodel/Template/0/1
      - TemplateManagement__TemplateMappingRules__SubmodelTemplateMappings__2__pattern__0=CustomSubmodel
      - TemplateManagement__TemplateMappingRules__ShellTemplateMappings__0__templateId=https://mm-software.com/aas/aasTemplate
      - TemplateManagement__TemplateMappingRules__ShellTemplateMappings__0__pattern__0=
      - TemplateManagement__TemplateMappingRules__AasIdExtractionRules__0__Strategy=Split
      - TemplateManagement__TemplateMappingRules__AasIdExtractionRules__0__Pattern=/
      - TemplateManagement__TemplateMappingRules__AasIdExtractionRules__0__Index=5
      - TemplateManagement__AasTemplateRepository__Name=AasTemplateRepository
      - TemplateManagement__AasTemplateRepository__baseUrl=http://template-repository:8081
      - TemplateManagement__AasTemplateRepository__headerMappings__0__source=Authorization
      - TemplateManagement__AasTemplateRepository__headerMappings__0__target=Authorization
      - TemplateManagement__AasTemplateRepository__headerMappings__0__required=false
      - TemplateManagement__SubmodelTemplateRepository__Name=SubmodelTemplateRepository
      - TemplateManagement__SubmodelTemplateRepository__baseUrl=http://template-repository:8081
      - TemplateManagement__SubmodelTemplateRepository__headerMappings__0__source=Authorization
      - TemplateManagement__SubmodelTemplateRepository__headerMappings__0__target=Authorization
      - TemplateManagement__SubmodelTemplateRepository__headerMappings__0__required=false
      - TemplateManagement__ConceptDescriptionTemplateRepository__Name=ConceptDescriptionTemplateRepository
      - TemplateManagement__ConceptDescriptionTemplateRepository__baseUrl=http://template-repository:8081
      - TemplateManagement__ConceptDescriptionTemplateRepository__headerMappings__0__source=Authorization
      - TemplateManagement__ConceptDescriptionTemplateRepository__headerMappings__0__target=Authorization
      - TemplateManagement__ConceptDescriptionTemplateRepository__headerMappings__0__required=false
      - TemplateManagement__AasTemplateRegistry__Name=AasTemplateRegistry
      - TemplateManagement__AasTemplateRegistry__baseUrl=http://aas-template-registry:8080
      - TemplateManagement__AasTemplateRegistry__headerMappings__0__source=Authorization
      - TemplateManagement__AasTemplateRegistry__headerMappings__0__target=Authorization
      - TemplateManagement__AasTemplateRegistry__headerMappings__0__required=false
      - TemplateManagement__SubmodelTemplateRegistry__Name=SubmodelTemplateRegistry
      - TemplateManagement__SubmodelTemplateRegistry__baseUrl=http://sm-template-registry:8080
      - TemplateManagement__SubmodelTemplateRegistry__headerMappings__0__source=Authorization
      - TemplateManagement__SubmodelTemplateRegistry__headerMappings__0__target=Authorization
      - TemplateManagement__SubmodelTemplateRegistry__headerMappings__0__required=false
    networks:
      - dataengine-network

  twinengine-plugin:
    build:
      context: ../../
      dockerfile: ./AAS.TwinEngine.Plugin.TestPlugin/Dockerfile
    image: twinengine-plugin:latest
    ports:
    - '8086:8080'
    container_name: twinengine-plugin
    restart: always
    volumes:
      - ./plugin/mock-metadata.json:/App/Data/mock-metadata.json
      - ./plugin/mock-submodel-data.json:/App/Data/mock-submodel-data.json
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Semantics__IndexContextPrefix=_aastwinengineindex_
      - Capabilities__HasShellDescriptor=true
      - Capabilities__HasAssetInformation=true
    networks:
      - dataengine-network

  template-repository:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: template-repository
    ports:
      - "8081:8081"
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    environment:
      BASYX_EXTERNALURL : http://localhost:8080
    restart: always
    depends_on:
      aas-template-registry:
        condition: service_healthy
      sm-template-registry:
        condition: service_healthy
    networks:
      - dataengine-network

  aas-template-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-template-registry
    ports:
      - '8082:8080'
    restart: always
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoAdmin:mongoPassword@mongo:27017
    networks:
      - dataengine-network

  sm-template-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: sm-template-registry
    ports:
      - '8083:8080'
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongoAdmin:mongoPassword@mongo:27017
    networks:
      - dataengine-network

  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-ui
    volumes:
      - ./logo:/usr/src/app/dist/Logo
    environment:
      AAS_REGISTRY_PATH: http://localhost:8080/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8080/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8080/shells
      SUBMODEL_REPO_PATH: http://localhost:8080/submodels
      CD_REPO_PATH: http://localhost:8080/concept-descriptions
      BASE_PATH: "/aas-ui"
      LOGO_PATH: "MM_Logo.svg"
      PRIMARY_DARK_COLOR: "#00F2E5"
      PRIMARY_LIGHT_COLOR: "#041b2b"
    restart: always
    depends_on:
      template-repository:
        condition: service_healthy
    networks:
      - dataengine-network

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoPassword
    networks:
      - dataengine-network
